language: python
sudo: false
python:
  - "2.7.6"
  - "2.7"
  - "3.6"
addons:
  apt:
    packages:
      - enchant
install:
  - pip install -U pip wheel
  - pip install -U setuptools
  - pip install -r requirements.txt
script:
  - make flake8
  - make
notifications:
  slack: ccnmtl:GizSNscLWJLldjQrffB8mwgm
