# Generated by Django 3.2.12 on 2022-04-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_virtual_patient', '0002_auto_20150612_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1),
        ),
        migrations.AlterField(
            model_name='patientassessmentblock',
            name='view',
            field=models.IntegerField(choices=[(0, 'Treatment Options'), (1, 'Best Treatment Option'), (2, 'Prescription'), (3, 'Results')]),
        ),
        migrations.AlterField(
            model_name='treatmentfeedback',
            name='combination_therapy',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatmentfeedback',
            name='correct_dosage',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='treatmentoptionreasoning',
            name='combination',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
