# Generated by Django 4.2.16 on 2024-09-27 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220408_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_not_participant',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='consent_participant',
        ),
    ]
