# Generated by Django 4.2.16 on 2024-09-27 20:04

from django.db import models, migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_userprofile_consent_not_participant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='consent_not_participant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='consent_participant',
            field=models.BooleanField(default=False),
        ),
    ]
