name: build-and-test
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
          python-version: ["3.8", "3.12"]
    steps:
      - uses: actions/checkout@v5
      - name: Run eslint
        run: make eslint
      - name: Build with Makefile
        run: make
